logging:
  level:
    root: INFO # Reduce global noise (was DEBUG by default in dev)
    org.springframework: WARN # Suppress most Spring internals
    com.nhp: INFO # Your package — keep this at DEBUG to see your own logs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,mappings
  metrics:
    export:
      prometheus:
        enabled: true
